application/json: >-
  #set($allParams = $input.params())
  {
  "body" : $input.json('$'),
  "params" : {
  "multiValueQueryStringParameters": {
      #foreach($key in $method.request.multivaluequerystring.keySet())
      "$key" : [
        #foreach($val in $method.request.multivaluequerystring.get($key))
       "$val"#if($foreach.hasNext),#end
        #end
        ]#if($foreach.hasNext),#end
      #end
    }
     #if($allParams.size() > 1),#end
  #foreach($type in $allParams.keySet())
      #set($params = $allParams.get($type))
  "$type" : {
      #foreach($paramName in $params.keySet())
      "$paramName" : "$util.escapeJavaScript($params.get($paramName))"
          #if($foreach.hasNext),#end
      #end
  }
      #if($foreach.hasNext),#end
  #end
  },
  "stage-variables" : {
  #foreach($key in $stageVariables.keySet())
  "$key" : "$util.escapeJavaScript($stageVariables.get($key))"
      #if($foreach.hasNext),#end
  #end
  },
  "context" : {
      "account-id" : "$context.identity.accountId",
      "api-id" : "$context.apiId",
      "api-key" : "$context.identity.apiKey",
      "caller" : "$context.identity.caller",
      "http-method" : "$context.httpMethod",
      "stage" : "$context.stage",
      "source-ip" : "$context.identity.sourceIp",
      "user" : "$context.identity.user",
      "user-agent" : "$context.identity.userAgent",
      "user-arn" : "$context.identity.userArn",
      "request-id" : "$context.requestId",
      "resource-id" : "$context.resourceId",
      "resource-path" : "$context.resourcePath"
      }
  }
