paths:
  "/traveler-form":
    post:
      tags:
        - traveler form
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "201":
          description: 201 response
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${aws_region}:${aws_account}:function:traveler_form_create/invocations
        httpMethod: POST
        responses:
          default:
            statusCode: "201"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              $ref: ../../common/modules/api-gateway/swagger/response/application-json.yaml
        requestTemplates:
          $ref: ../../common/modules/api-gateway/swagger/request/application-json.yaml
        passthroughBehavior: when_no_templates
        contentHandling: CONVERT_TO_TEXT
    options:
      $ref: ../../common/modules/api-gateway/swagger/options/option.yaml
