---
swagger: "2.0"
info:
  version: "2021-02-22T11:39:56Z"
  title: "Traveler_form_api"
basePath: "v1"
schemes:
  - "https"
paths:
securityDefinitions:
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
tags:
  - name: "traveler form"
    description: "Allow to create or get a traveler form"
