name: "CI/CD Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-validate-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check for code changes
        id: check_files
        run: |
          echo "::set-output name=src_changed::$(git diff --quiet HEAD^ HEAD packages/**/src/** || echo true)"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
        if: steps.check_files.outputs.src_changed

      - name: Install Dependencies
        run: yarn install
        if: steps.check_files.outputs.src_changed

      - name: Build
        run: yarn build
        if: steps.check_files.outputs.src_changed

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "traveler_form_web"
          SOURCE_DIR: "packages/web/build"
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
