name: "CI/CD Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-validate-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'packages/**/src/**'
            web:
              - 'packages/web/src/**'
            infra:
              - '*.tf'
              - '*.tfvars'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
        if: steps.changes.outputs.src == 'true'

      - name: Install Dependencies
        run: yarn install
        if: steps.changes.outputs.src == 'true'

      - name: Build
        run: yarn build
        if: steps.changes.outputs.src == 'true'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init
        if: steps.changes.outputs.infra == 'true'

      - name: Terraform Validate
        run: terraform validate
        if: steps.changes.outputs.infra == 'true'

      - name: Terraform Plan
        run: terraform plan
        if: steps.changes.outputs.infra == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "traveler-form-web"
          SOURCE_DIR: "packages/web/build"
        if: steps.changes.outputs.web == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
